# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/micha/Documents/Xilnux/VGA/vga_phase3/vga_phase3.srcs/sources_1/ip/blk_mem_gen_index/blk_mem_gen_index.xci
# IP: The module: 'blk_mem_gen_index' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/Xilnux/VGA/vga_phase3/vga_phase3.gen/sources_1/ip/blk_mem_gen_index/blk_mem_gen_index_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_index'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/micha/Documents/Xilnux/VGA/vga_phase3/vga_phase3.srcs/sources_1/ip/blk_mem_gen_index/blk_mem_gen_index.xci
# IP: The module: 'blk_mem_gen_index' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/Xilnux/VGA/vga_phase3/vga_phase3.gen/sources_1/ip/blk_mem_gen_index/blk_mem_gen_index_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_index'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
